columns:
longitude: float
latitude: float
housing_median_age: float
total_rooms: float
total_bedrooms: float
population: float
households: float
median_income: float
median_house_value: float
ocean_proximity: float
income_cat: category


target_column: median_house_value

domain_value:
  ocean_proximity:
    - <1 OCEAN
    - INLAND
    - ISLAND
    - NEAR BAY
    - NEAR OCEAN
    
